language: node_js

node_js:
  - 0.10

before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in deploy_key.enc -out deploy_key -d

install : npm install
script  : npm start

after_success:
  - node -e 'p=process;p.exit(p.argv[1]==="Alexey Anshakov"?0:1)' `git log -1 --format='%an'`
  - npm version patch
  - chmod 600 deploy_key
  - ssh-add deploy_key
  - git config --global user.email "alexey.anshakov@gmail.com"
  - git config --global user.name "AlexeyAnshakov"
  - git remote add deploy_repo git@github.com/webRunes/Titter-WRIO-App.git
  - git add package.json
  - git commit -m 'ver'
  - git push deploy_repo

deploy:
  - provider: opsworks
    access_key_id:
      secure: CpJ6OYeiTKJ/SYlne4/oAJCxUOiviGYjEc6h/E3A7Tfbyu9baNN4mv821WKRgiRar9tqNrBrzQ7n/eSdzu/IK5rWnG+vuYzj5BoDINRsdvbQpICvpIB88xdE6bvRRaUQrLVUUVxc4GZXCwL8jP72ohz09FpU9HQlUq1V6AzQtF8=
    secret_access_key:
      secure: FNq2Va9UYwqYayTKbMLQiq6mUcRe2f3aAK9jLOKfMsW1gx6Y6bwtWNzaocH0aAC2m4vheH2rktzvy0604g6YDPh2lPgD4/9JvQi6/x4UwXzzKzTHyDtAuSg5zEYie0/h5HhHKmOm/YeXIMh3msqqy9+bfsWKDG7rdihynZqprG8=
    app-id: 4539a5ac-9d5f-4ce1-bbac-e3456b3b4c22
    on:
      repo: webRunes/Titter-WRIO-App
  - provider: s3
    access_key_id:
      secure: mR+kXkYTSLM50ICSs7Fm29iFpJo8jCsyYKiyF8ZlBhzmSP8GoHpcsSWd6J/HFnW1WQqa6vAmv/Sxd1Lr23AnxtKyGm+ROej2QQWrp2EouHLEFxuOwy2whLDqAvQcyZyi4eRqeWicAFhM/qrkK4EdvgbsgBqXIY9RXEH1y6Hgxi4=
    secret_access_key:
      secure: G3QfqVMapeaGxersv8Oumdc9QWSnCNmq70hJNmD8OrFgOhKj7F48+uv9WLoBAJxw31WIBBWqMSY9l7CO3ur9plPwL+Gfda7yGUE8HDBMJ/pukL2DAzwd1pu/iPlt/+HMO4YYIDJZsDpSWN5PvxAf+MtsG7hXJUlJSy/nwpvpZ3M=
    bucket: wrioos.com
    upload-dir: Titter-WRIO-App
    acl: public_read

